# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e2417abec5fd5979878937e7dc181f772ee987fced9b5a17ee370c479b3af65fe8e5cb075488bc6563320608e3f2eb16580f651109eb59aaa725521ffac2dc

test:
  secret_key_base: 17a8be337b45e9c1cc86bd9e50e573b85f32f25207dcf70dc8b17eb657a94c8bb98384fdd35697f34810e2253746213e6c6f275684e58100a4009c8ff9a310a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
